server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버
    url: jdbc:mysql://3.35.3.47:3306/bulletin
    username: user1
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
